vich_uploader:
  db_driver: orm

  mappings:
    video_file:
      uri_prefix: /uploads/videos
      upload_destination: '%kernel.project_dir%/public/uploads/videos'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
